import { authHeader, request, requestBody } from './http.js'

/**
 * `/api/users` — account management, grown from L11 task 3 into fiche 17's
 * full lifecycle: invitations, search/pagination/bulk actions, a
 * self-service public profile, dormant/MFA signals, and anonymization.
 *
 * Every call here is permission-checked on the server; nothing in this file is
 * a security boundary. The admin hides what it knows a role cannot do so the
 * screen is not full of buttons that fail, but the refusal that matters is the
 * 403 the router produces (R4).
 */

export interface MfaSummary {
  readonly totp: boolean
  readonly passkeys: number
}

/**
 * `invited` and `anonymized` join `active`/`disabled` for the same reason
 * `@cogenta/auth`'s `UserStatus` does — see that type's doc comment. Neither
 * is reachable through `updateUser`'s generic `PATCH`: an invitation is
 * created via `inviteUser`/turned active by the invitee redeeming their
 * token, and anonymization is `anonymizeUser`, one-way.
 */
export type AdminUserStatus = 'active' | 'disabled' | 'invited' | 'anonymized'

export interface PendingInvitation {
  readonly sentAt: string
  readonly expiresAt: string
}

export interface AdminUser {
  readonly id: string
  readonly email: string
  /** Public profile (fiche 17 task 3) — `null` means not set, never an empty string. */
  readonly displayName: string | null
  readonly avatarMediaId: string | null
  readonly bio: string | null
  readonly locale: string | null
  readonly roles: readonly string[]
  readonly status: AdminUserStatus
  readonly createdAt: string
  readonly updatedAt: string
  readonly mfa: MfaSummary
  /** A sensitive role (ADR-0021) with no second factor enrolled. Never a gate — see `packages/auth/src/mfa.ts`. */
  readonly mfaRecommended: boolean
  readonly lastSignInAt: string | null
  /** No activity for longer than the site's dormant threshold — a possibly-forgotten door, not a violation. */
  readonly dormant: boolean
  /** Only set while `status === 'invited'`. */
  readonly invitation: PendingInvitation | null
}

export interface UserSession {
  readonly id: string
  readonly createdAt: string
  readonly expiresAt: string
  readonly lastSeenAt: string
  readonly label: string | null
  /** Distilled from the `User-Agent` at sign-in (fiche 18 task 2) — never a raw IP or user-agent string, see `@cogenta/auth`'s `parseUserAgent`. */
  readonly browser: string
  readonly device: string
  /** Whether this is the session making the current request. Only ever true on your own list — see `revokeOtherSessions`. */
  readonly isCurrent: boolean
}

export interface CreatedUser {
  readonly user: AdminUser
  readonly invited: boolean
  readonly emailSent: boolean
  /**
   * Generated by the server and returned exactly once — it is stored only as
   * a hash. Present only on the R1 fallback path: absent whenever `invited`
   * is `true`.
   */
  readonly password?: string
}

export interface ListUsersOptions {
  readonly role?: string
  /** Substring match on email or display name — see `users-router.ts`'s `q` handling. */
  readonly q?: string
  readonly sort?: 'createdAt' | 'lastSignInAt'
  readonly direction?: 'asc' | 'desc'
  readonly limit?: number
  /** Opaque — always the previous page's `nextCursor`, never constructed by hand. */
  readonly after?: string
}

export interface UsersPage {
  readonly users: readonly AdminUser[]
  readonly hasMore: boolean
  readonly nextCursor: string | null
  /** Whether the site can actually send an invitation mail (fiche 17 task 1's R1 fallback). */
  readonly invitationEmailAvailable: boolean
}

function usersQuery(options: ListUsersOptions): string {
  const params = new URLSearchParams()
  if (options.role !== undefined && options.role !== '') params.set('role', options.role)
  if (options.q !== undefined && options.q.trim().length > 0) params.set('q', options.q)
  if (options.sort !== undefined) {
    params.set('sort', `${options.sort}:${options.direction ?? 'asc'}`)
  }
  if (options.limit !== undefined) params.set('limit', String(options.limit))
  if (options.after !== undefined) params.set('after', options.after)
  return params.toString()
}

/**
 * Kept returning a plain array, byte for byte, for the callers that only ever
 * wanted "every account matching this filter" — `global-search.tsx` chief
 * among them. `listUsersPage` below is the one the accounts screen itself
 * uses for real pagination and the invitation-availability flag.
 */
export function listUsers(
  token: string,
  options: ListUsersOptions = {},
): Promise<readonly AdminUser[]> {
  const query = usersQuery(options)
  return request(`/api/users${query === '' ? '' : `?${query}`}`, { headers: authHeader(token) })
}

export async function listUsersPage(
  token: string,
  options: ListUsersOptions = {},
): Promise<UsersPage> {
  const query = usersQuery(options)
  const response = await requestBody<{
    data: readonly AdminUser[]
    page: { hasMore: boolean; nextCursor: string | null }
    meta: { invitationEmailAvailable: boolean }
  }>(`/api/users${query === '' ? '' : `?${query}`}`, { headers: authHeader(token) })
  return {
    users: response.data,
    hasMore: response.page.hasMore,
    nextCursor: response.page.nextCursor,
    invitationEmailAvailable: response.meta.invitationEmailAvailable,
  }
}

export function createUser(
  token: string,
  input: { readonly email: string; readonly roles: readonly string[]; readonly invite?: boolean },
): Promise<CreatedUser> {
  return request('/api/users', {
    method: 'POST',
    headers: authHeader(token),
    body: JSON.stringify(input),
  })
}

/** Sugar over `createUser` for the invitation path — fiche 17 task 1. */
export function inviteUser(
  token: string,
  input: { readonly email: string; readonly roles: readonly string[] },
): Promise<CreatedUser> {
  return createUser(token, { ...input, invite: true })
}

export function resendInvitation(
  token: string,
  id: string,
): Promise<{ invited: boolean; expiresAt: string }> {
  return request(`/api/users/${encodeURIComponent(id)}/invite`, {
    method: 'POST',
    headers: authHeader(token),
  })
}

export async function cancelInvitation(token: string, id: string): Promise<void> {
  await request(`/api/users/${encodeURIComponent(id)}/invite`, {
    method: 'DELETE',
    headers: authHeader(token),
  })
}

export function updateUser(
  token: string,
  id: string,
  changes: { readonly roles?: readonly string[]; readonly status?: 'active' | 'disabled' },
): Promise<AdminUser> {
  return request(`/api/users/${encodeURIComponent(id)}`, {
    method: 'PATCH',
    headers: authHeader(token),
    body: JSON.stringify(changes),
  })
}

export interface BulkUsersResult {
  readonly succeeded: readonly string[]
  readonly failed: readonly { id: string; error: string; code?: string }[]
}

/** Fiche 17 task 2 — never partly silent: every failure is named in the response. */
export function bulkUpdateUsers(
  token: string,
  input:
    | { readonly action: 'disable' | 'enable'; readonly ids: readonly string[] }
    | {
        readonly action: 'setRoles'
        readonly ids: readonly string[]
        readonly roles: readonly string[]
      },
): Promise<BulkUsersResult> {
  return request('/api/users/bulk', {
    method: 'POST',
    headers: authHeader(token),
    body: JSON.stringify(input),
  })
}

/** `id` may be `me`: the server resolves it to whoever the token belongs to. */
export function readUser(token: string, id: string): Promise<AdminUser> {
  return request(`/api/users/${encodeURIComponent(id)}`, { headers: authHeader(token) })
}

/**
 * Self-service only (fiche 17 task 3) — there is no admin-editable path for
 * somebody else's name, bio or avatar, mirroring the rule that already holds
 * for a password.
 */
export function updateOwnProfile(
  token: string,
  changes: {
    readonly displayName?: string | null
    readonly avatarMediaId?: string | null
    readonly bio?: string | null
    readonly locale?: string | null
  },
): Promise<AdminUser> {
  return request('/api/users/me/profile', {
    method: 'PATCH',
    headers: authHeader(token),
    body: JSON.stringify(changes),
  })
}

/**
 * Fiche 17 task 5 — irreversible. `confirmEmail` must match the account's
 * *current* address exactly; the server refuses otherwise rather than
 * guessing what was meant.
 */
export async function anonymizeUser(
  token: string,
  id: string,
  confirmEmail: string,
): Promise<void> {
  await request(`/api/users/${encodeURIComponent(id)}/anonymize`, {
    method: 'POST',
    headers: authHeader(token),
    body: JSON.stringify({ confirmEmail }),
  })
}

export function listUserSessions(token: string, id: string): Promise<readonly UserSession[]> {
  return request(`/api/users/${encodeURIComponent(id)}/sessions`, { headers: authHeader(token) })
}

export async function revokeUserSession(
  token: string,
  id: string,
  sessionId: string,
): Promise<void> {
  await request(`/api/users/${encodeURIComponent(id)}/sessions/${encodeURIComponent(sessionId)}`, {
    method: 'DELETE',
    headers: authHeader(token),
  })
}

/**
 * "Déconnecter toutes les autres sessions" (fiche 18 task 2) — self only,
 * always relative to the session making this very call, which is what the
 * `me` here means: there is no such thing as "my other sessions" on someone
 * else's account.
 */
export function revokeOtherSessions(
  token: string,
): Promise<{ readonly revoked: number; readonly keptSessionId: string }> {
  return request('/api/users/me/sessions/revoke-others', {
    method: 'POST',
    headers: authHeader(token),
  })
}

export async function changeOwnPassword(
  token: string,
  currentPassword: string,
  newPassword: string,
): Promise<void> {
  await request('/api/users/me/password', {
    method: 'POST',
    headers: authHeader(token),
    body: JSON.stringify({ currentPassword, newPassword }),
  })
}

/**
 * Mirrors `@cogenta/export`'s `PersonalDataExport` — kept as a local shape
 * rather than a new dependency on `@cogenta/export` (R9), the same way this
 * file already re-declares the server's user shape as `AdminUser`.
 */
export interface PersonalDataExport {
  readonly generatedAt: string
  readonly subjectEmail: string
  readonly account: {
    readonly id: string
    readonly email: string
    readonly roles: readonly string[]
    readonly status: string
    readonly createdAt: string
  } | null
  readonly authoredContent: readonly {
    readonly collection: string
    readonly id: string
    readonly status: string
    readonly createdAt: string
    readonly title: string | null
  }[]
  readonly orders: readonly {
    readonly id: string
    readonly status: string
    readonly createdAt: string
    readonly totalMinorUnits: number
    readonly currency: string
  }[]
  readonly gaps: readonly { readonly source: string; readonly reason: string }[]
}

/**
 * T09-04 (RGPD) — self or `admin`, the same rule `/{id}` itself follows.
 * The export is itself journalled server-side; this call has nothing more
 * to do than fetch and hand the caller a downloadable blob.
 */
export function fetchPersonalDataExport(token: string, id: string): Promise<PersonalDataExport> {
  return request(`/api/users/${encodeURIComponent(id)}/personal-data`, {
    headers: authHeader(token),
  })
}
