import { authHeader, request } from './http.js'

/**
 * `/api/users` — account management, L11 task 3.
 *
 * Every call here is permission-checked on the server; nothing in this file is
 * a security boundary. The admin hides what it knows a role cannot do so the
 * screen is not full of buttons that fail, but the refusal that matters is the
 * 403 the router produces (R4).
 */

export interface MfaSummary {
  readonly totp: boolean
  readonly passkeys: number
}

export interface AdminUser {
  readonly id: string
  readonly email: string
  readonly roles: readonly string[]
  readonly status: 'active' | 'disabled'
  readonly createdAt: string
  readonly updatedAt: string
  readonly mfa: MfaSummary
}

export interface UserSession {
  readonly id: string
  readonly createdAt: string
  readonly expiresAt: string
  readonly lastSeenAt: string
  readonly label: string | null
}

export interface CreatedUser {
  readonly user: AdminUser
  /** Generated by the server and returned exactly once — it is stored only as a hash. */
  readonly password: string
}

export function listUsers(token: string, role?: string): Promise<readonly AdminUser[]> {
  const query = role === undefined || role === '' ? '' : `?role=${encodeURIComponent(role)}`
  return request(`/api/users${query}`, { headers: authHeader(token) })
}

export function createUser(
  token: string,
  input: { readonly email: string; readonly roles: readonly string[] },
): Promise<CreatedUser> {
  return request('/api/users', {
    method: 'POST',
    headers: authHeader(token),
    body: JSON.stringify(input),
  })
}

export function updateUser(
  token: string,
  id: string,
  changes: { readonly roles?: readonly string[]; readonly status?: 'active' | 'disabled' },
): Promise<AdminUser> {
  return request(`/api/users/${encodeURIComponent(id)}`, {
    method: 'PATCH',
    headers: authHeader(token),
    body: JSON.stringify(changes),
  })
}

/** `id` may be `me`: the server resolves it to whoever the token belongs to. */
export function readUser(token: string, id: string): Promise<AdminUser> {
  return request(`/api/users/${encodeURIComponent(id)}`, { headers: authHeader(token) })
}

export function listUserSessions(token: string, id: string): Promise<readonly UserSession[]> {
  return request(`/api/users/${encodeURIComponent(id)}/sessions`, { headers: authHeader(token) })
}

export async function revokeUserSession(
  token: string,
  id: string,
  sessionId: string,
): Promise<void> {
  await request(`/api/users/${encodeURIComponent(id)}/sessions/${encodeURIComponent(sessionId)}`, {
    method: 'DELETE',
    headers: authHeader(token),
  })
}

export async function changeOwnPassword(
  token: string,
  currentPassword: string,
  newPassword: string,
): Promise<void> {
  await request('/api/users/me/password', {
    method: 'POST',
    headers: authHeader(token),
    body: JSON.stringify({ currentPassword, newPassword }),
  })
}
