import { validateCollectionSet } from './define-collection.js'
import type { CollectionDefinition, FieldDefinition } from './types.js'
import { isCollectionValued } from './validation.js'

/**
 * Renders `.cogenta/types.d.ts`.
 *
 * This function only builds the string; writing it is the CLI's job. That split
 * keeps the generator pure, therefore comparable character by character in a
 * test, and usable from a watch loop without touching the disk.
 *
 * The generated file is **self-contained on purpose**. A theme compiles against
 * it without depending on `@cogenta/schema`, which rule R5 wants kept out of
 * theme code anyway. That is what makes a theme referencing a field that no
 * longer exists fail to compile — the acceptance criterion of L1.
 */

const HEADER = `// Generated by Cogenta. Do not edit.
//
// Run \`cogenta generate\` after changing a collection: this file is derived from
// your schema, and editing it by hand only delays the next overwrite.

`

/** Shared shapes, emitted whether or not every collection uses them. */
const PRELUDE = `/** Application-minted UUIDv7 (ADR-0015). */
export type CogentaId = string

export type JsonValue =
  | string
  | number
  | boolean
  | null
  | JsonValue[]
  | { [key: string]: JsonValue }

export interface GeoPoint {
  readonly lat: number
  readonly lng: number
  readonly label?: string
}

export type ContentStatus = 'draft' | 'scheduled' | 'published' | 'archived'

export type Provenance = 'human' | 'assisted' | 'generated'

export interface ProvenanceDetail {
  readonly agent?: string
  readonly model?: string
  readonly at?: string
  readonly prompt?: string
}

export interface RichTextSpan {
  readonly _key: string
  readonly _type: 'span'
  readonly text: string
  readonly marks: readonly string[]
}

export type RichTextMarkDefinition =
  | { readonly _key: string; readonly _type: 'link'; readonly href: string; readonly rel?: string }
  | {
      readonly _key: string
      readonly _type: 'internalLink'
      readonly collection: string
      readonly id: CogentaId
    }

export interface RichTextBlock {
  readonly _key: string
  readonly _type: 'block'
  readonly style: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
  readonly listItem?: 'bullet' | 'number'
  readonly level?: number
  readonly children: readonly RichTextSpan[]
  readonly markDefs: readonly RichTextMarkDefinition[]
}

export interface RichTextMedia {
  readonly _key: string
  readonly _type: 'media'
  readonly id: CogentaId
  readonly caption?: string
}

export type RichTextNode = RichTextBlock | RichTextMedia

export type RichTextDocument = readonly RichTextNode[]

export interface ContentBlock {
  readonly _key: string
  readonly _type: string
  readonly [field: string]: unknown
}

/** Present on every entry, never declared by a collection. */
export interface SystemFields {
  readonly id: CogentaId
  readonly createdAt: string
  readonly updatedAt: string
  readonly createdBy: CogentaId | null
  readonly updatedBy: CogentaId | null
  readonly status: ContentStatus
  readonly locale: string
  readonly translationOf: CogentaId | null
  readonly version: number
  readonly provenance: Provenance
  readonly provenanceDetail: ProvenanceDetail | null
}
`

export function renderTypeDeclarations(collections: readonly CollectionDefinition[]): string {
  validateCollectionSet(collections)

  // Sorted by name so that reordering the imports in a schema file does not
  // produce a diff in the generated output.
  const sorted = [...collections].sort((left, right) => (left.name < right.name ? -1 : 1))

  const parts: string[] = [HEADER, PRELUDE]

  for (const collection of sorted) {
    parts.push('\n', renderCollection(collection))
  }

  parts.push('\n', renderRegistry(sorted))

  return parts.join('')
}

function renderCollection(collection: CollectionDefinition): string {
  const lines: string[] = []
  lines.push(`/** ${collection.labels.plural} */`)
  lines.push(`export interface ${interfaceName(collection.name)} extends SystemFields {`)

  for (const [name, field] of Object.entries(collection.fields)) {
    const doc = documentationFor(field)
    if (doc !== undefined) lines.push(`  /** ${doc} */`)
    lines.push(`  readonly ${propertyName(name)}: ${typeOf(field)}`)
  }

  lines.push('}', '')
  return lines.join('\n')
}

function renderRegistry(collections: readonly CollectionDefinition[]): string {
  const lines: string[] = []
  lines.push('/** Every collection of this site, by name. */')
  lines.push('export interface CollectionTypes {')
  for (const collection of collections) {
    lines.push(`  readonly ${propertyName(collection.name)}: ${interfaceName(collection.name)}`)
  }
  lines.push('}', '')
  lines.push('export type CollectionName = keyof CollectionTypes')
  lines.push('')
  return lines.join('\n')
}

/** `blog_post` becomes `BlogPost`; the name is already validated as an identifier. */
export function interfaceName(collectionName: string): string {
  return collectionName
    .split(/[-_]/)
    .filter((part) => part !== '')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('')
}

const PLAIN_PROPERTY = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function propertyName(name: string): string {
  return PLAIN_PROPERTY.test(name) ? name : quote(name)
}

function documentationFor(field: FieldDefinition): string | undefined {
  const parts = [field.admin?.label, field.admin?.help].filter(
    (part): part is string => part !== undefined && part !== '',
  )
  if (field.localized === true) parts.push('Translated field.')
  return parts.length === 0 ? undefined : parts.join(' — ').replaceAll('*/', '*\\/')
}

function typeOf(field: FieldDefinition): string {
  const base = baseTypeOf(field)
  // A field holding several values is never null: its empty case is `[]`, since
  // a join table with no rows says exactly that.
  if (field.required === true || isCollectionValued(field)) return base
  // Otherwise `| null` rather than `?`: the key always exists once the row is
  // read, and a theme that forgets the empty case should hear about it at
  // compile time rather than render "undefined".
  return `${base} | null`
}

function baseTypeOf(field: FieldDefinition): string {
  switch (field.kind) {
    case 'text':
    case 'slug':
    case 'color':
    case 'date':
    case 'datetime':
      return 'string'
    case 'richText':
      return 'RichTextDocument'
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'media':
    case 'relation':
      return field.options.many === true ? 'readonly CogentaId[]' : 'CogentaId'
    case 'select': {
      const union = selectUnion(field)
      return field.options.many === true ? `readonly (${union})[]` : union
    }
    case 'json':
      return 'JsonValue'
    case 'geo':
      return 'GeoPoint'
    case 'blocks':
      return 'readonly ContentBlock[]'
    default:
      // Unreachable: `defineCollection` rejects an unknown kind before this.
      return 'unknown'
  }
}

function selectUnion(field: FieldDefinition): string {
  const options = field.options.options
  if (!Array.isArray(options) || options.length === 0) return 'string'
  return options
    .map((choice) =>
      typeof choice === 'object' && choice !== null && 'value' in choice
        ? String((choice as { value: unknown }).value)
        : String(choice),
    )
    .map(quote)
    .join(' | ')
}

function quote(value: string): string {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}
