import { chooseStrategy } from './strategy.js'
import { serviceWorkerMain, tombstoneMain } from './sw-runtime.js'
import type { PwaConfig } from './types.js'
import { cacheNameFor, cachesToPurge } from './version.js'

/**
 * Generation of the service worker script.
 *
 * ## The update strategy, stated in full
 *
 * `skipWaiting()` and `clients.claim()` are two calls; the strategy is the four
 * properties that make those two calls safe.
 *
 * **1. Every generation owns its caches.** Cache names embed a version derived
 * from the offline page, the precache list and the route table
 * (`computeCacheVersion`). A new deploy therefore writes into new caches and
 * cannot mix generations, which is what makes immediate activation safe: there
 * is no window in which half the entries are old.
 *
 * **2. Activation purges the previous generations.** `cachesToPurge` returns
 * every cache of ours whose version is not the current one, and activation
 * deletes them before claiming clients. Storage does not accumulate one
 * generation per deploy, and — the part that matters — yesterday's HTML is
 * *gone*, not merely lower priority.
 *
 * **3. Documents are never served from cache while the network works.** Even a
 * worker that somehow survived a bad deploy cannot pin an old page: the
 * document strategy is network-first, so the cache answers only when the
 * network has already failed. This is the property that keeps a mistake
 * recoverable by deploying a fix, rather than requiring every visitor to clear
 * their site data.
 *
 * **4. There is an exit.** The worker answers a message by purging every cache
 * it owns and calling `registration.unregister()` — that is the admin's "clear
 * client cache" button. For clients we can no longer run code on,
 * `renderTombstoneServiceWorker` produces a worker that unregisters itself on
 * activation; deploying it at the same URL removes the PWA from every browser
 * that re-fetches the script, which browsers do at least daily.
 *
 * ## What is deliberately *not* done
 *
 * The worker does not reload open pages when it activates. A forced reload
 * destroys scroll position, half-typed comments and video playback, and it
 * turns one bad deploy into a reload loop. It posts `cogenta:activated`
 * instead, and the page decides — the registration helper in `client.ts` turns
 * that into an "a new version is available" prompt.
 *
 * The worker is a *classic* script, not an ES module: module workers are still
 * unevenly supported, and there is nothing to import — the script is
 * self-contained by construction.
 */

/**
 * Headers the server must send for the service worker script.
 *
 * This is not decoration. A worker script cached by the HTTP cache for a year
 * is the canonical unkillable zombie: the browser's daily update check reads
 * the stale copy from disk, sees no change, and keeps the old worker alive —
 * including after the tombstone has been deployed. `no-cache` (revalidate, do
 * not blindly reuse) is the minimum, and the scope header lets the script live
 * anywhere while controlling the whole origin.
 */
export const SERVICE_WORKER_HEADERS: Readonly<Record<string, string>> = {
  'cache-control': 'no-cache, max-age=0, must-revalidate',
  'content-type': 'text/javascript; charset=utf-8',
  'service-worker-allowed': '/',
}

/**
 * `Function.prototype.toString` returns the source of the function itself; the
 * `export` keyword is a separate declaration in the module grammar. Stripping
 * it anyway costs one line and removes a dependency on that detail of whichever
 * engine ran `tsc`.
 */
function sourceOf(fn: (...args: never[]) => unknown): string {
  return String(fn).replace(/^export\s+/, '')
}

const BANNER = [
  '/*',
  ' * Generated by @cogenta/render. Do not edit: this file is rewritten on every',
  ' * build, and its content determines the cache generation.',
  ' *',
  ' * Serve it with `cache-control: no-cache` (see SERVICE_WORKER_HEADERS). A',
  ' * worker script held in the HTTP cache cannot be updated or removed.',
  ' */',
].join('\n')

function scriptFor(body: string): string {
  return `${BANNER}\n${body}\n`
}

export function renderServiceWorker(config: PwaConfig): string {
  // Pretty-printed on purpose: this file is the first thing anyone reads when a
  // browser is serving something unexpected, and a minified route table is
  // unreadable at exactly that moment.
  const configLiteral = JSON.stringify(config, null, 2)

  return scriptFor(
    [
      `const COGENTA_PWA_CONFIG = ${configLiteral}\n`,
      sourceOf(cacheNameFor),
      sourceOf(cachesToPurge),
      sourceOf(chooseStrategy),
      sourceOf(serviceWorkerMain),
      '',
      'serviceWorkerMain(self, COGENTA_PWA_CONFIG)',
    ].join('\n\n'),
  )
}

/**
 * The kill switch, as a deployable artefact.
 *
 * Deploy this at the URL the real worker was served from. It caches nothing,
 * intercepts nothing, deletes every cache under `cachePrefix` and unregisters
 * itself. Keep it deployed for at least one update cycle — twenty-four hours
 * covers browsers that only check the script once a day — before removing the
 * route entirely, because a 404 on the worker URL also unregisters the worker
 * but tells the caches nothing.
 */
export function renderTombstoneServiceWorker(cachePrefix: string): string {
  return scriptFor(
    [
      `const COGENTA_CACHE_PREFIX = ${JSON.stringify(cachePrefix)}\n`,
      sourceOf(tombstoneMain),
      '',
      'tombstoneMain(self, COGENTA_CACHE_PREFIX)',
    ].join('\n\n'),
  )
}
