/**
 * Colour parsing and WCAG contrast, written by hand.
 *
 * Why no dependency: a colour library is a supply-chain surface, and the whole
 * point of the skin validator is that a skin generated by a model in L9 is safe
 * *by construction*. The rules it enforces must be auditable in one file, not
 * inherited from a package that may change its rounding next minor version.
 */

export interface Rgb {
  readonly r: number
  readonly g: number
  readonly b: number
}

export interface Rgba extends Rgb {
  /** 0 = fully transparent, 1 = fully opaque. */
  readonly a: number
}

/** WCAG 2.2 AA thresholds. Large text is >=18.66px bold or >=24px regular. */
export const AA_NORMAL_TEXT = 4.5
export const AA_LARGE_TEXT = 3

export type TextSize = 'normal' | 'large'

export function aaThreshold(size: TextSize): number {
  return size === 'large' ? AA_LARGE_TEXT : AA_NORMAL_TEXT
}

const HEX = /^#([0-9a-f]{3,8})$/i
const FUNCTIONAL = /^(rgb|rgba|hsl|hsla)\(([^()]*)\)$/i

/**
 * Parses a CSS colour. The accepted set is deliberately closed to hex, `rgb()`
 * and `hsl()`: named colours, `color()` and `oklch()` would each need their own
 * conversion path before a contrast ratio could be computed, and a colour whose
 * luminance cannot be computed cannot be validated — so it must not be accepted.
 *
 * Returns `null` rather than throwing: the caller owns the error, because only
 * the caller knows which token the value came from.
 */
export function parseColor(value: string): Rgba | null {
  const input = value.trim()

  const hex = HEX.exec(input)
  if (hex !== null) {
    return parseHex(hex[1] ?? '')
  }

  const fn = FUNCTIONAL.exec(input)
  if (fn !== null) {
    const name = (fn[1] ?? '').toLowerCase()
    const parts = splitArguments(fn[2] ?? '')
    if (parts === null) {
      return null
    }
    return name.startsWith('rgb') ? parseRgbArgs(parts) : parseHslArgs(parts)
  }

  return null
}

function parseHex(digits: string): Rgba | null {
  const expand = (pair: string): number => Number.parseInt(pair, 16)
  if (digits.length === 3 || digits.length === 4) {
    const channels = [...digits].map((c) => expand(c + c))
    return toRgba(channels)
  }
  if (digits.length === 6 || digits.length === 8) {
    const channels: number[] = []
    for (let i = 0; i < digits.length; i += 2) {
      channels.push(expand(digits.slice(i, i + 2)))
    }
    return toRgba(channels)
  }
  return null
}

function toRgba(channels: readonly number[]): Rgba | null {
  const [r, g, b, a] = channels
  if (r === undefined || g === undefined || b === undefined) {
    return null
  }
  if (![r, g, b].every(Number.isFinite)) {
    return null
  }
  return { r, g, b, a: a === undefined ? 1 : a / 255 }
}

/** Accepts both the legacy comma syntax and the modern `r g b / a` syntax. */
function splitArguments(raw: string): string[] | null {
  const [head, ...rest] = raw.split('/')
  if (rest.length > 1 || head === undefined) {
    return null
  }
  const first = head.trim()
  const values = first.includes(',')
    ? first.split(',').map((p) => p.trim())
    : first.split(/\s+/).filter((p) => p !== '')
  if (rest.length === 1) {
    values.push((rest[0] ?? '').trim())
  }
  return values.length === 3 || values.length === 4 ? values : null
}

function parseNumber(raw: string, percentBasis: number): number | null {
  const text = raw.trim()
  if (text === '') {
    return null
  }
  const isPercent = text.endsWith('%')
  const parsed = Number(isPercent ? text.slice(0, -1) : text)
  if (!Number.isFinite(parsed)) {
    return null
  }
  return isPercent ? (parsed / 100) * percentBasis : parsed
}

function clamp(value: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, value))
}

function parseAlpha(raw: string | undefined): number | null {
  if (raw === undefined) {
    return 1
  }
  const value = parseNumber(raw, 1)
  return value === null ? null : clamp(value, 0, 1)
}

function parseRgbArgs(parts: readonly string[]): Rgba | null {
  const alpha = parseAlpha(parts[3])
  const r = parseNumber(parts[0] ?? '', 255)
  const g = parseNumber(parts[1] ?? '', 255)
  const b = parseNumber(parts[2] ?? '', 255)
  if (alpha === null || r === null || g === null || b === null) {
    return null
  }
  return { r: clamp(r, 0, 255), g: clamp(g, 0, 255), b: clamp(b, 0, 255), a: alpha }
}

function parseHslArgs(parts: readonly string[]): Rgba | null {
  const rawHue = parts[0] ?? ''
  const hue = Number(rawHue.replace(/deg$/i, ''))
  const saturation = parseNumber(parts[1] ?? '', 1)
  const lightness = parseNumber(parts[2] ?? '', 1)
  const alpha = parseAlpha(parts[3])
  if (!Number.isFinite(hue) || saturation === null || lightness === null || alpha === null) {
    return null
  }
  return { ...hslToRgb(hue, clamp(saturation, 0, 1), clamp(lightness, 0, 1)), a: alpha }
}

function hslToRgb(hue: number, s: number, l: number): Rgb {
  // CSS Color 4 reference implementation, kept literal so it stays checkable.
  const h = ((hue % 360) + 360) % 360
  const channel = (n: number): number => {
    const k = (n + h / 30) % 12
    const a = s * Math.min(l, 1 - l)
    return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1))
  }
  return { r: channel(0) * 255, g: channel(8) * 255, b: channel(4) * 255 }
}

/** WCAG 2.2 relative luminance. */
export function relativeLuminance(color: Rgb): number {
  const linear = (channel: number): number => {
    const c = clamp(channel, 0, 255) / 255
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4
  }
  return 0.2126 * linear(color.r) + 0.7152 * linear(color.g) + 0.0722 * linear(color.b)
}

/** WCAG 2.2 contrast ratio, between 1 and 21. */
export function contrastRatio(a: Rgb, b: Rgb): number {
  const la = relativeLuminance(a)
  const lb = relativeLuminance(b)
  const lighter = Math.max(la, lb)
  const darker = Math.min(la, lb)
  return (lighter + 0.05) / (darker + 0.05)
}

/**
 * Composites a translucent foreground over an opaque background. A contrast
 * ratio computed on the raw foreground of a translucent colour is wrong — and
 * wrong in the optimistic direction — so it is composited first.
 */
export function compositeOver(foreground: Rgba, background: Rgb): Rgb {
  const a = clamp(foreground.a, 0, 1)
  return {
    r: foreground.r * a + background.r * (1 - a),
    g: foreground.g * a + background.g * (1 - a),
    b: foreground.b * a + background.b * (1 - a),
  }
}

/**
 * No epsilon on purpose. A pair at 4.4999:1 is below AA; rounding it up to
 * "4.50" is exactly the kind of leniency that makes the guarantee a lie.
 */
export function meetsContrastAa(ratio: number, size: TextSize): boolean {
  return ratio >= aaThreshold(size)
}

/** Two decimals, the precision every WCAG reporting tool uses. */
export function formatRatio(ratio: number): string {
  return `${(Math.floor(ratio * 100) / 100).toFixed(2)}:1`
}
