import type { Density, SkinTokens } from './tokens.js'
import { TOKEN_SPECS } from './tokens.js'
import { computeTypeScale } from './validate.js'

/**
 * Renders a validated skin as one stylesheet of custom properties.
 *
 * One sheet, no build step: this file *is* the skin. Swapping a skin rewrites
 * it, and nothing downstream has to be recompiled — which is what makes hot
 * swap possible at all (contract D, "changement de skin = réécriture de ce
 * fichier, sans build").
 */

export const CSS_VARIABLE_PREFIX = '--cogenta'

/** `accentFg` → `accent-fg`. The variable name is part of the theme API. */
export function kebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase()
}

export function cssVariableName(group: string, name: string): string {
  return `${CSS_VARIABLE_PREFIX}-${group}-${kebab(name)}`
}

/**
 * Density is a word, and a word cannot be multiplied by a spacing unit. The
 * multiplier is what a theme can actually compute with; the word is kept too,
 * for container queries and debugging.
 */
const DENSITY_SCALE: Record<Density, string> = {
  compact: '0.75',
  comfortable: '1',
  spacious: '1.25',
}

function declaration(name: string, value: string): string {
  return `  ${name}: ${value};`
}

export interface RenderSkinCssOptions {
  /** Selector the variables are attached to. `:root` unless a preview scopes it. */
  readonly selector?: string
}

export function renderSkinCss(tokens: SkinTokens, options: RenderSkinCssOptions = {}): string {
  const selector = options.selector ?? ':root'
  const lines: string[] = []

  // TOKEN_SPECS drives the order, so the output is byte-stable for a given
  // skin: a stable sheet means a stable ETag, and a cache that behaves.
  for (const spec of TOKEN_SPECS) {
    // The group types are object type aliases on purpose: they carry an
    // implicit index signature, so a token can be read by name without a cast.
    const group: Readonly<Record<string, string | number | boolean>> = tokens[spec.group]
    lines.push(declaration(cssVariableName(spec.group, spec.name), String(group[spec.name])))
  }

  lines.push(declaration(`${CSS_VARIABLE_PREFIX}-space-scale`, DENSITY_SCALE[tokens.space.density]))

  const scale = computeTypeScale(tokens)
  for (const [step, size] of Object.entries(scale)) {
    lines.push(declaration(`${CSS_VARIABLE_PREFIX}-font-size-${step}`, size))
  }

  const reducedMotion = [
    '@media (prefers-reduced-motion: reduce) {',
    `  ${selector} {`,
    `  ${declaration(`${CSS_VARIABLE_PREFIX}-motion-duration`, '0ms')}`,
    `  ${declaration(`${CSS_VARIABLE_PREFIX}-motion-easing`, 'linear')}`,
    '  }',
    '}',
  ].join('\n')

  return [
    '/* Generated by @cogenta/render — skin tokens. Do not edit by hand. */',
    `${selector} {`,
    ...lines,
    '}',
    '',
    // The declared `motion.reduced` is worth nothing unless the sheet acts on
    // it, so the media query is emitted from the same source as the tokens
    // and cannot drift away from them.
    reducedMotion,
    '',
  ].join('\n')
}
